# Generated by Django 3.2.13 on 2022-07-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_postings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_id', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('j_post', models.TextField()),
            ],
        ),
    ]
