# Generated by Django 3.2.13 on 2022-07-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_postings',
            name='main_img',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
    ]
