# Generated by Django 3.2.13 on 2022-07-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_img',
            field=models.ImageField(default=' ', upload_to='images'),
        ),
    ]
