# Generated by Django 3.2.13 on 2022-07-23 05:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_profile_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(default=False),
        ),
    ]
